spring:
  application:
    name: bts-api

  datasource:
    url: jdbc:mysql://localhost:3306/bts?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root   # 또는 root
    password: dltnqls11
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.MySQLDialect  # (원하면만) / 아니면 아예 제거

jwt:
  secret: "bts-api-jwt-secret-key-2026-very-secure-string"
  access-exp-min: 60

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG